/*
 * This source file was generated by the Gradle 'init' task
 */
package vision.code;

import edu.wpi.first.cscore.UsbCamera;

public class App {

  public static void main(String[] args) {
    UsbCamera camera = new UsbCamera("TEST", 0);
    System.out.println(camera.getActualFPS());
    camera.close();
  }
}
